# .streamlit/config.toml
[theme]
primaryColor = "#4CAF50"  # Example: Green
backgroundColor = "#F5F5F5"  # Light gray background
secondaryBackgroundColor = "#FFFFFF"  # White cards
textColor = "#333333"  # Dark text
font = "sans serif"  # Professional font
st.markdown(
    """
    <style>
        .header {
            font-size: 36px;
            color: #4CAF50;
            text-align: center;
            font-weight: bold;
            padding: 10px;
        }
        .subheader {
            font-size: 20px;
            color: #555555;
            text-align: center;
        }
    </style>
    """,
    unsafe_allow_html=True
)

st.markdown('<div class="header">DataPilot</div>', unsafe_allow_html=True)
st.markdown('<div class="subheader">Your Interactive Machine Learning Dashboard</div>', unsafe_allow_html=True)
col1, col2 = st.columns([2, 1])  # Adjust proportions

with col1:
    st.subheader("Upload Your Dataset")
    uploaded_file = st.file_uploader("Choose a CSV file", type="csv")

with col2:
    st.image("path_to_image.png", width=200)  # Add a logo or relevant image
tab1, tab2, tab3 = st.tabs(["🏠 Home", "📊 Data Visualization", "🤖 Model Training"])

with tab1:
    st.write("Welcome to DataPilot!")

with tab2:
    st.write("Data Visualization section here.")

with tab3:
    st.write("Model Training section here.")
st.markdown("### 🔍 Explore Your Data")
st.markdown("### 📊 Build Powerful Models")
st.markdown("### 🎯 Achieve Results")
st.sidebar.title("Settings")
st.sidebar.markdown("Adjust your preferences:")
st.sidebar.slider("Train-Test Split Ratio", 0.1, 0.5, 0.2, 0.05)
st.sidebar.radio("Choose Theme", ["Light", "Dark", "System Default"])
import seaborn as sns
sns.set_theme(style="whitegrid")  # Professional theme for plots

# Example: Customizing a histogram
plt.figure(figsize=(8, 6))
sns.histplot(data['column_name'], bins=20, color="#4CAF50", kde=True)
plt.title("Distribution of Column", fontsize=16, color="#333333")
plt.xlabel("Values", fontsize=12)
plt.ylabel("Frequency", fontsize=12)
st.pyplot(plt)
with st.spinner("Training your model..."):
    # Simulate long-running process
    time.sleep(5)  # Replace with actual training code
st.success("Model trained successfully!")
st.markdown(
    """
    <hr>
    <div style='text-align: center;'>
        <small>Powered by DataPilot &copy; 2024</small>
    </div>
    """,
    unsafe_allow_html=True
)
